### ISSUE TITLE
Bug detecting and problems about SMAI

### ISSUE THREAD

**Issue by HelloWorldLTY** [rongstat/SMAI#1]
Hi, I tried SMAI to test if two datasets are alignable or not, and had a series of findings.

The first thing I intend to share are two bugs. One for example dataset:
![image](https://github.com/rongstat/SMAI/assets/43333475/f336da06-d3b3-4415-8d64-a98121a4fb54)
I have installed seuratDisk

Another one is for my own dataset:
![image](https://github.com/rongstat/SMAI/assets/43333475/906a3fb4-9f7a-4d18-9963-f29d6ebdc746)

Could you please help me address them? Thanks a lot.

Moreover, another question is from the algorithm 1. I found that different seeds generated different p values. I think this algorithm does not contrain permutation, so there should be no randomness in p-value.

![image](https://github.com/rongstat/SMAI/assets/43333475/a0dd6eaa-dce2-44f2-b6a4-fa06601b5771)

And if we found that two datasets are not alignable, why this algorithm still "aligns" them? 

Thanks a lot.

**Comment by rongstat** [comment]
Thank you so much for raising the issues! 

1. One probably needs to first install the "pbmcsca" dataset using `InstallData("pbmcsca")`, before loading the data - sorry about that! Corrections have been made in the Tutorial.

2. The error "prop.align too large!" indicates insufficient size for the maximal correspondence subsets identified in the previous step, which can be fixed by increasing the parameter `k1` in function `findMutualNN()`. To improve automation in this step, we have updated the corresponding codes in our Tutorial - a suitable `k1` is now determined automatically, without user specification.

3. For our partial alignability test, we incorporate a sample splitting procedure to ensure its statistical validity, which introduces randomness to our test result. However, one may benefit from such randomness by repeating the test under various random seeds, to assess the robustness/stability of the test results with respect to resampling.

4. You are right, the final integrated datasets are returned regardless of the significance of the p-value. Our test essentially indicates the goodness-of-fit of the data generative model motivating the proposed alignment procedure, but does not necessarily affect the execution of the alignment algorithm. However, we do recommend not using the integrated data if a significant p-value is returned.

Please let me know if you have further questions/comments! Thank a lot!

**Comment by HelloWorldLTY** [comment]
Thanks for your reply! I will try your method based on the updated version again.

**Comment by rongstat** [comment]
Of course! Please let me know if you have further questions!

**Comment by HelloWorldLTY** [comment]
Thanks a lot.
